### ISSUE TITLE
Separar storyboard de análise de tarefas no planejamento da avaliação e na avaliação em si

### ISSUE THREAD

**Issue by ErickGiffoni** [Interacao-Humano-Computador/2020.1-Prefeiturade-Aguas-Lindas-de-Goias#7]
Pessoal, embora os storyboards de vcs sejam baseados nas <br>
tarefas anteriormente apresentadas na análise de tarefas, é interessante <br>
separar a avaliação e o relato dessa avaliação com respeito ao storyboard <br>
e à análise de tarefas.

Isso porque, até então, o storyboard foi avaliado junto à análise de tarefa, <br>
segundo o que está na wiki.

**Comment by ErickGiffoni** [comment]
Além disso, notei que a documentação sobre as avaliações que vcs fizeram
estão um pouco diferentes, então seria interessante padronizar o formato da escrita
(tópicos, utilização de negrito... coisas desse tipo)

**Comment by brunaalmeidasantos** [comment]
Os documentos foram refatorados, e as avaliações das tarefas e dos storyboards foram separadas.
